# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x07greeter\"\x1e\n\x0bTestMessage\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1e\n\x0cTestResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2B\n\x07Greeter\x12\x37\n\x08SendData\x12\x14.greeter.TestMessage\x1a\x15.greeter.TestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTMESSAGE']._serialized_start=26
  _globals['_TESTMESSAGE']._serialized_end=56
  _globals['_TESTRESPONSE']._serialized_start=58
  _globals['_TESTRESPONSE']._serialized_end=88
  _globals['_GREETER']._serialized_start=90
  _globals['_GREETER']._serialized_end=156
# @@protoc_insertion_point(module_scope)
